# Generated by Django 4.1.3 on 2022-11-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=16)),
                ('movie', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'liked',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.TextField()),
                ('imdb', models.CharField(max_length=100, unique=True)),
                ('mc', models.CharField(blank=True, max_length=100, null=True)),
                ('rt', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('cast', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'titles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Towatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=16)),
                ('movie', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'towatch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=16)),
                ('movie', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'watched',
                'managed': False,
            },
        ),
    ]
