# Generated by Django 4.1.3 on 2022-11-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liked',
            options={},
        ),
        migrations.AlterModelOptions(
            name='towatch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='watched',
            options={},
        ),
    ]
