# Generated by Django 4.1.3 on 2022-11-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_liked_options_alter_towatch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liked',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='towatch',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='watched',
            options={'managed': False},
        ),
    ]
