# Generated by Django 4.1.3 on 2022-11-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_liked_options_alter_towatch_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(blank=True, max_length=300, null=True)),
                ('lang', models.CharField(blank=True, max_length=20, null=True)),
                ('runtime', models.CharField(blank=True, max_length=20, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('plot', models.CharField(blank=True, max_length=500, null=True)),
                ('rimdb', models.CharField(blank=True, max_length=10, null=True)),
                ('r1mc', models.CharField(blank=True, max_length=10, null=True)),
                ('r2mc', models.CharField(blank=True, max_length=10, null=True)),
                ('mc1r', models.CharField(blank=True, max_length=10, null=True)),
                ('mc1', models.CharField(blank=True, max_length=1000, null=True)),
                ('mc2r', models.CharField(blank=True, max_length=10, null=True)),
                ('mc2', models.CharField(blank=True, max_length=1000, null=True)),
                ('imdb1r', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb1h', models.CharField(blank=True, max_length=100, null=True)),
                ('imdb1', models.CharField(blank=True, max_length=1000, null=True)),
                ('imdb2r', models.CharField(blank=True, max_length=10, null=True)),
                ('imdb2h', models.CharField(blank=True, max_length=100, null=True)),
                ('imdb2', models.CharField(blank=True, max_length=1000, null=True)),
                ('seasoninfo', models.CharField(blank=True, max_length=200, null=True)),
                ('rt1', models.CharField(blank=True, max_length=1000, null=True)),
                ('rt2', models.CharField(blank=True, max_length=1000, null=True)),
                ('year', models.CharField(blank=True, max_length=15, null=True)),
                ('r1rt', models.CharField(blank=True, max_length=10, null=True)),
                ('r2rt', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('cast', models.CharField(blank=True, max_length=150, null=True)),
                ('sim1', models.IntegerField(blank=True, null=True)),
                ('sim1h', models.CharField(blank=True, max_length=300, null=True)),
                ('sim2', models.IntegerField(blank=True, null=True)),
                ('sim2h', models.CharField(blank=True, max_length=300, null=True)),
                ('sim3', models.IntegerField(blank=True, null=True)),
                ('sim3h', models.CharField(blank=True, max_length=300, null=True)),
                ('sim4', models.IntegerField(blank=True, null=True)),
                ('sim4h', models.CharField(blank=True, max_length=300, null=True)),
                ('v', models.CharField(blank=True, max_length=300, null=True)),
                ('p', models.CharField(blank=True, max_length=300, null=True)),
                ('amc', models.CharField(blank=True, max_length=300, null=True)),
                ('nf', models.CharField(blank=True, max_length=300, null=True)),
                ('h', models.CharField(blank=True, max_length=300, null=True)),
                ('ap', models.CharField(blank=True, max_length=300, null=True)),
                ('dp', models.CharField(blank=True, max_length=300, null=True)),
                ('hm', models.CharField(blank=True, max_length=300, null=True)),
                ('pp', models.CharField(blank=True, max_length=300, null=True)),
                ('atp', models.CharField(blank=True, max_length=300, null=True)),
                ('s', models.CharField(blank=True, max_length=300, null=True)),
                ('a', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cache',
                'managed': False,
            },
        ),
    ]
